name: Build Expo iOS & Android

on:
  push:
    branches:
      - main  # Cambiá si tu rama principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4️⃣ Instalar EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # 5️⃣ Configurar token de Expo
      - name: Set Expo token
        run: echo "${{ secrets.EXPO_TOKEN }}" > ~/.eas/token
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # 6️⃣ Build iOS
      - name: Build iOS
        run: eas build -p ios --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # 7️⃣ Build Android
      - name: Build Android
        run: eas build -p android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}